### ISSUE TITLE
发现一个低级严重的bug

### ISSUE THREAD

**Issue by justmehyp** [banq/jdonframework#13]
![image](https://user-images.githubusercontent.com/20594467/44527528-a770ab00-a719-11e8-8c82-331f3e1e6dc7.png)

![image](https://user-images.githubusercontent.com/20594467/44527550-c0795c00-a719-11e8-99e9-fc12efde7a8a.png)

**Comment by justmehyp** [comment]
跑个demo遇到的错误，改了一下代码可以跑起来了，但是不知道理解的对不对，刚开始学习，多多指教。
![image](https://user-images.githubusercontent.com/20594467/44528417-16e79a00-a71c-11e8-80c2-908b17daa5f0.png)
![image](https://user-images.githubusercontent.com/20594467/44528499-51e9cd80-a71c-11e8-8b5c-aa925f5e0d5b.png)
![image](https://user-images.githubusercontent.com/20594467/44528533-6332da00-a71c-11e8-826f-b3dd00f59bb4.png)

**Comment by banq** [comment]
非常感谢，这应该是个bug
